nos = {
    "C-AD":"Adega",
    "C-BC":"bebidas e Churrasco",
    "C-LI":"laticíno",
    "C-HF":"hortfruti",
    "C-C1":"caixa 1",
    "C-PL":"produtos de limpeza",
    "C-E1":"entrada 1",
    "C-CR":"caixa rápido",
    "C-PF":"perfumaria",
    "C-OO":"ovos",
    "C-C2":"caixa 2",
    "C-LR":"lataria",
    "C-MS":"massas",
    "C-CG":"congelados",
    "C-E2":"entrada 2",
    "C-FR":"flores",
    "C-MT":"matinais",
    "C-FT":"festas",
    "C-DB":"doces e bolos",
    "C-ST":"sanitarios",
    "C-AT":"atendimento",
    "C-CS":"cereais",
    "C-LT":"leite"
}