nos = {
    "A":"Entrada",
    "B":"Saída",
    "C":"Caixas",
    "D":"Flores",
    "E":"Adega",
    "F":"Bebidas e Churrasco",
    "H":"Perfumaria",
    "I":"Massas",
    "J":"Biscoito",
    "K":"Laticínios",
    "L":"Hortifruti",
    "M":"Congelados",
    "N":"Doces",
    "O":"Açougue",
}